reshuffled around again

diff --git a/hass-addons/rootfs/etc/supervisor/common b/hass-addons/rootfs/etc/supervisor/common
--- a/hass-addons/rootfs/etc/supervisor/common
+++ b/hass-addons/rootfs/etc/supervisor/common
@@ -1,21 +1,18 @@
 #!/bin/bash
 
-set -e
+set -x
 
-# shellcheck disable=SC1091
-source "/etc/container/src.sh"
+function prepare_supervisor()
+{
+    sudo rm /etc/machine-id
+    sudo dbus-uuidgen --ensure=/etc/machine-id
 
-VERSION_INFO=$(curl -s https://version.home-assistant.io/dev.json)
-HA_ARCH=$(get_arch ha)
-DOCKER_TIMEOUT=30
-SUPERVISOR_SHARE="/mnt/supervisor"
-
-export SUPERVISOR_VERSION
-SUPERVISOR_VERSION=$(echo "${VERSION_INFO}" | jq -e -r '.supervisor')
-
-export SUPERVISOR_IMAGE
-SUPERVISOR_IMAGE=$(echo "${VERSION_INFO}" | jq -e -r '.images.supervisor' | sed "s|{arch}|${HA_ARCH}|g")
-
+    if grep -q 'microsoft-standard\|standard-WSL' /proc/version; then
+        # The docker daemon does not start when running WSL2 without adjusting iptables
+        sudo update-alternatives --set iptables /usr/sbin/iptables-legacy || echo "Fails adjust iptables"
+        sudo update-alternatives --set ip6tables /usr/sbin/ip6tables-legacy || echo "Fails adjust ip6tables"
+    fi
+}
 
 function start_systemd_journald() {
     if ! [ -e /var/log/journal ]; then
@@ -168,7 +165,7 @@ function init_os_agent() {
 }
 
 
-validate_devcontainer() {
+function validate_devcontainer() {
     local devcontainer_type="$1"
 
     if ! grep -q "$SUPERVISOR_SHARE" /proc/mounts; then
